version: "3.9"

services:

  api:
    build: .
    container_name: taxi_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build: .
    container_name: taxi_worker
    command: celery -A celery_config.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:latest
    container_name: CONTAINER
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - "5434:5432"  # ← Changed back to 5433 to match your app's connection string
    volumes:
      - pgdata:/var/lib/postgresql  # ← FIXED: mount the parent directory

volumes:
  pgdata:
